version: '3.5'
services:
 web_dev:
  build: webapp
  command: bash -c "/wait && ./startup"
  ports:
   - "80:5000"
  volumes:
   - .:/app
  environment:
    WAIT_HOSTS: mongodb:27017
 mongodb:
  build: database
  container_name: "mongodb"
  volumes:
   - mongodb:/data/db
networks:
 default:
volumes:
  mongodb:
